### PR TITLE
Added some bright colours functions for non tty terminals.

### PR DESCRIPTION
**Pull request by Indomian**
- redBright, greenBright etc.

Signed-off-by: Egor Bolgov e.bolgov@semrush.com

### CODE REVIEW

**Comment by alanshaw** [comment]
Could you write some tests for this to prove it works? I think you'll need to upgrade the `cli-color` dependency. If that's the case we need to support the full API for the upgraded dependency.

**Comment by Indomian** [comment]
Well i tested in my own application, could write some tests, but later i think. I'll check whats new in **cli-color** so we can provide full functionality upgrade.

**Comment by Indomian** [comment]
Added some tests to prove that changes is Ok. Checked updates of **cli-color** - seems like thay added pretty much functions, and i required only colour ones, so I suggest to stop on this for now.

**Comment by alanshaw** [comment]
:thumbsup:

**Comment by Indomian** [comment]
Thank you

**Pull request merged**
